#!/usr/bin/env bash
# One-time bootstrap of the remote Terraform state backend (Option B).
# Creates a resource group + storage account + container, hardens the account,
# and writes terraform/backend.hcl. Idempotent: re-runs reuse the existing
# storage account recorded in backend.hcl.
#
#   ./scripts/bootstrap-state.sh
# Overridable via env: TF_STATE_RG, TF_STATE_SA, TF_STATE_CONTAINER, TF_STATE_LOCATION
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."   # -> terraform/

LOCATION="${TF_STATE_LOCATION:-eastus}"
RG="${TF_STATE_RG:-rg-tfstate-emp}"
CONTAINER="${TF_STATE_CONTAINER:-tfstate}"
BACKEND_FILE="backend.hcl"

log() { printf '\033[1;34m[+]\033[0m %s\n' "$*"; }

command -v az >/dev/null || { echo "az CLI is required"; exit 1; }
az account show >/dev/null 2>&1 || { echo "Run 'az login' first."; exit 1; }

# Reuse an existing storage account name if backend.hcl already exists.
EXISTING_SA=""
if [[ -f "${BACKEND_FILE}" ]]; then
  EXISTING_SA="$(grep -E '^\s*storage_account_name' "${BACKEND_FILE}" | sed -E 's/.*"(.*)".*/\1/' || true)"
fi
SA="${TF_STATE_SA:-${EXISTING_SA:-sttfemp$(openssl rand -hex 3)}}"

log "Subscription : $(az account show --query name -o tsv)"
log "Resource grp : ${RG}   Region: ${LOCATION}"
log "Storage acct : ${SA}   Container: ${CONTAINER}"

log "Creating resource group"
az group create -n "${RG}" -l "${LOCATION}" --only-show-errors -o none

log "Creating hardened storage account (TLS1.2, no public blob access, LRS)"
az storage account create -n "${SA}" -g "${RG}" -l "${LOCATION}" \
  --sku Standard_LRS --kind StorageV2 --min-tls-version TLS1_2 \
  --allow-blob-public-access false --https-only true \
  --only-show-errors -o none

log "Enabling blob versioning + 7-day soft delete (state recovery)"
az storage account blob-service-properties update \
  --account-name "${SA}" -g "${RG}" \
  --enable-versioning true --enable-delete-retention true --delete-retention-days 7 \
  --only-show-errors -o none

log "Creating state container"
az storage container create -n "${CONTAINER}" --account-name "${SA}" \
  --auth-mode login --only-show-errors -o none 2>/dev/null \
  || az storage container create -n "${CONTAINER}" --account-name "${SA}" \
       --only-show-errors -o none

cat > "${BACKEND_FILE}" <<EOF
# Generated by scripts/bootstrap-state.sh — shared remote state backend.
# No secrets here; safe to commit. Per-env state key is passed at init time.
resource_group_name  = "${RG}"
storage_account_name = "${SA}"
container_name       = "${CONTAINER}"
EOF

log "Wrote ${BACKEND_FILE}. Now: make tf-plan TF_ENV=dev"
