---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-management-frontend
  labels:
    app.kubernetes.io/name: employee-management
    app.kubernetes.io/instance: employee-management
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: employee-management
    environment: "default"
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-management-frontend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-management-backend
  labels:
    app.kubernetes.io/name: employee-management
    app.kubernetes.io/instance: employee-management
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: employee-management
    environment: "default"
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-management-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 30
