apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-management-config
data:
  ENVIRONMENT: stage
  LOG_LEVEL: info
  ACCESS_TOKEN_EXPIRE_MINUTES: "240"
  CORS_ORIGINS: "https://employee.stage.sidhuge.xyz"
