# Generated by scripts/bootstrap-state.sh — shared remote state backend.
# No secrets here; safe to commit. Per-env state key is passed at init time.
resource_group_name  = "rg-tfstate-emp"
storage_account_name = "sttfemp1dfe38"
container_name       = "tfstate"
