apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-management-config
data:
  ENVIRONMENT: prod
  LOG_LEVEL: warning
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  CORS_ORIGINS: "https://employee.sidhuge.xyz"
