---
apiVersion: v1
kind: Service
metadata:
  name: employee-management-frontend
  labels:
    app.kubernetes.io/name: employee-management
    app.kubernetes.io/instance: employee-management
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: employee-management
    environment: "default"
    app.kubernetes.io/component: frontend
spec:
  # ClusterIP: exposed to the outside world only through the Ingress.
  type: ClusterIP
  selector:
    app.kubernetes.io/name: employee-management
    app.kubernetes.io/instance: employee-management
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
